export enum TASK_OPERATIONS {
    CREATE_TASK = "CREATE_TASK",
    DELETE_TASK = "DELETE_TASK",
    MODIFY_TASK = "MODIFY_TASK",
    SET_ACTIVE_TASK = "SET_ACTIVE_TASK",
    CHECK_DONE_TASKS = "CHECK_DONE_TASKS",
    TOGGLE_TASK = "TOGGLE_TASK",


}

export enum POMODORO_OPERATIONS {
    CREATE_POMODORO = "CREATE_POMODORO",
    DELETE_POMODORO = "DELETE_POMODORO",
    PAUSE_POMODORO = "PAUSE_POMODORO",
    START_POMODORO = "START_POMODORO"
}